In [2]:
import pandas as pd
import numpy as np
from numpy import *
from numpy.linalg import *

In [3]:
dataset = pd.read_csv('50_Startups.csv')
X = dataset.iloc[ : , : -1].values
Y = dataset.iloc[ : , 4 ].values

In [4]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder = LabelEncoder()
X[ : , 3] = labelencoder.fit_transform(X[ : , 3])
onehotencoder = OneHotEncoder(categorical_features = [3])
X = onehotencoder.fit_transform(X).toarray()

In [5]:
X = X[: , 1:]


In [6]:
from sklearn.cross_validation import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

C:\Users\Harden Zeng\Anaconda3\lib\site-packages\sklearn\cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [7]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [8]:
Y_pred = regressor.predict(X_test)
Y_pred

array([ 103015.20159795,  132582.27760817,  132447.73845176,
         71976.09851257,  178537.48221058,  116161.24230165,
         67851.69209675,   98791.73374686,  113969.43533013,
        167921.06569553])

In [9]:
Y_test

array([ 103282.38,  144259.4 ,  146121.95,   77798.83,  191050.39,
        105008.31,   81229.06,   97483.56,  110352.25,  166187.94])

In [10]:
K = Y_pred - Y_test

In [11]:
K = (Y_test - Y_pred)/Y_test

In [12]:
K*100

array([  0.2586873 ,   8.09453137,   9.35808176,   7.48434326,
         6.54953271, -10.62099971,  16.46869717,  -1.34194294,
        -3.27785372,  -1.04287092])

In [16]:
import LR_zeng

In [17]:
LR_zeng.fit(X_test, Y_test)

NameError: name 'ones' is not defined

In [18]:
ones((2,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])